# Site settings
title: Your Blog Title
author:
  name: Bharath Kumar
  email: maxmod98@gmail.com
description: "A description of your blog or website"

# Build settings
remote_theme: jekyll/minima

# Optional settings
permalink: /:categories/:year/:month/:day/:title/
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO settings
url: "https://brucewayne98.github.io"
baseurl: ""
