# Site settings
title: "Bharath Kumar"
email: maxmod98@email.com
description: "Personal blog about system design, .NET, and cloud architecture"
url: "https://brucewayne98.github.io"
baseurl: ""
github_username: BruceWayne98

# Build settings
markdown: kramdown
timezone: Asia/Kolkata
permalink: /:title.html

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 5
paginate_path: "/page:num/"

author:
  name: "Bharath Kumar"
  bio: "Software Developer | .NET & Azure Enthusiast"
  avatar: "/assets/images/profile.jpg"
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/BruceWayne98"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bharath-kumar-r98"

# Navigation structure
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  # tag archives
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
      layout: tag
      entries_layout: list
  # tag pages
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
      entries_layout: list
      show_excerpts: true

# Archives
tag_archive:
  type: liquid
  path: /tags/
  
# Collection for tag pages
collections:
  tags:
    output: true
    permalink: /tags/:name/

include:
  - _pages
